### ISSUE TITLE
botox.Attribute does not work

### ISSUE THREAD

**Issue by marstein** [tmont/botox#1]
I am trying to do a `botox.attribute('BonifyServiceLambdaExecutionRole', 'Arn')` which results in an error `TypeError: botox.attribute is not a function`. This happens with both Attribute and attribute spellings. Am I doing something wrong?

I think the declaration below was left out of botox/index.js

```
    /**
     * Creates an attribute reference, e.g. Fn::GetAtt
     * @param {Object} resource
     * @param {String} attribute Name of the attribute
     */
    attribute: function(resource, attribute) {
        return new Functions.Attribute(resource, attribute);
    },
```

After I insert that things work.

Thanks!

**Comment by tmont** [comment]
The idea was that attributes are attached to resources. So you would create your (e.g.) EC2Instance object, and then call `instance.attr().privateDnsName` to get `{ Fn::GetAtt: [ 'myInstance', 'PrivateDNSName' ] }` or whatever.

There's an example in the readme on how attributes work.

Also, this was largely a toy for my own personal use, so there are probably lots of missing/incomplete features. If you find it useful, though, please open tickets/submit pull requests!

**Comment by tmont** [comment]
Link to README docs on attributes: https://github.com/tmont/botox#attributes

**Comment by marstein** [comment]
Very embarrassing. Sorry I missed the docs...

**Comment by marstein** [comment]
I find it quite useful, but am new to ApiGateway templates. The
intellisense works great for learning.

Sorry to bother you -- I have another problem, this time with a parameter:

const prefix = botox.parameter('DeploymentPrefix').type('String').description('Deployment
Prefix');

const serviceApiDeployment = botox.deployment('BonifyServiceAPIDevDeployment')
  .restApiId(serviceRestApi.id)
  .description('Bonify Service API deployment')
  .stageName('main')
  .stageDescription(botox.apiGatewayDeploymentStageDescription()
    .stageName('main')
    .description('Main/active stage')
    .variables({
      'dynamoTable': donationTable.ref,
      'lambdaName': botox.join([prefix, 'bonify-service'], '-')
    }));

This generates:

```
        "lambdaName": {
          "Fn::Join": [
            "-",
            [
              {
                "Ref": {
                  "Type": "String",
                  "Description": "Deployment Prefix"
                }
              },
              "bonify-service"
            ]
```

But should generate:

"lambdaName": {
  "Fn::Join": [
    "-",
    [
      {
        "Ref": "DeploymentPrefix"
      },
      "bonify-service"
    ]

Many thanks!
Martin

**Comment by tmont** [comment]
Try using what's in master instead of what's in NPM. My last commit a few months ago was to fix this very problem I believe.
